package com.empmgt.EmployeeManagementSystem.model;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Data //generate getters and setters , hashcodes
@Table(name="employees") //to give a customize table name
public class Employee {
    @Id // marks the id field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) //indicates id field as automatically generated by the database
    private long id;

    @Column(name="first_name")
    private String firstName;

    @Column(name="last_name")
    private String lastName;

    @Column(unique = true)
    private String email;

}
